config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, path_prefix: 'my'
    resources :users

    get 'welcome/index'
    root 'welcome#index'

    get '/search' => 'search#search', as: :search

    resources :advertisements
    resources :categories

    get '/my_advertisements' => 'advertisements#user_advertisements', :as => :custom_user_advertisements
    get '/opened_advertisements' => 'advertisements#opened_advertisements', :as => :opened_advertisements
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify

  after_create :assign_default_role

  has_many :advertisements, dependent: :destroy

  validates :username, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    has_role?(:admin)
  end

  def user?
    has_role?(:user)
  end

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_categories
  before_action :set_advertisements, only: %i[index edit]

  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @advertisements = @user.advertisements.order('updated_at DESC')
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, success: 'Пользователь успешно создан'
    else
      flash[:danger] = 'Ошибка при создании пользователя'
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, notice: 'Пользователь удален.' if @user.destroy
  end

  private

  def set_categories
    @categories = Category.all
  end

  def set_advertisements
    @advertisements = Advertisement.all.order(:id).reverse
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, role_ids: [])
  end
end

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.input :email, required: true, autofocus: true
  = f.input :username, required: true, autofocus: true
  = f.association :roles, as: :check_boxes
  = f.button :submit, class: "btn btn-primary"
  = link_to t('common.back'), :back, class: "btn btn-outline-secondary"

app/views/users/edit.html.slim
h1
  = t('user.edit.title')
= render 'form'

app/views/users/index.html.slim
h1
  = t('models.users')
table.table
  thead.thead-light
    tr
      th[scope="col"]
        | #
      th[scope="col"]
        = t('attributes.user.username')
      th[scope="col"]
        | Email
      th[scope="col"]
        = t('attributes.user.role')
      th[scope="col"]
  tbody
    - @users.each_with_index do |user, index|
      tr
        th[scope="row"]
          = index + 1
        td
          = link_to user.username, user_path(user)
        td
          = user.email
        td
          = user.roles.first.name
        td
          = link_to t('common.edit'), edit_user_path(user), class: 'btn btn-warning'
          = link_to t('common.delete'), admin_destroy_user_path(user), class: 'btn btn-danger',
                         method: :delete,
                         data: { confirm: 'Вы уверены?' }
= link_to t('devise.links.create_user'), new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
h1
  = t('user.new.title')
= simple_form_for(@user) do |f|
  = f.input :email, required: true, autofocus: true
  = f.input :username, required: true, autofocus: true
  = f.input :password,
                 required: true,
                 hint: ("(минимум #{@minimum_password_length} символов)" if @minimum_password_length),
                 input_html: { autocomplete: "new-password" }
  = f.association :roles, as: :check_boxes
  = f.button :submit, class: "btn btn-primary"
  = link_to t('common.back'), :back, class: "btn btn-outline-secondary"

app/views/users/show.html.slim
h1
  = t('user.user_ads', username: @user.username)
= render 'advertisements/advertisements'