config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, path_prefix: 'my'
    resources :users

    get 'welcome/index'
    root 'welcome#index'

    get '/search' => 'search#search', as: :search

    resources :advertisements
    resources :categories

    get '/my_advertisements' => 'advertisements#user_advertisements', :as => :custom_user_advertisements
    get '/opened_advertisements' => 'advertisements#opened_advertisements', :as => :opened_advertisements
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end
end

app/models/advertisement.rb
# frozen_string_literal: true

class Advertisement < ApplicationRecord
  include AdsSearch
  include StateMachine

  resourcify

  belongs_to :category
  belongs_to :user

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  validates :ad_title, presence: true,
                       length: { minimum: 5, maximum: 50 }
  validates :ad_text, presence: true,
                      length: { minimum: 100, maximum: 1000 }
  validates :category_id, presence: true

  filterrific default_filter_params: { sorted_by: 'created_at_desc' },
              available_filters: %w[
                sorted_by
                with_category_id
                with_created_at_gte
              ]

  # default for will_paginate
  self.per_page = 10

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = sort_option =~ /desc$/ ? 'desc' : 'asc'
    advertisements = Advertisement.arel_table
    categories = Category.arel_table
    case sort_option.to_s
    when /^created_at_/
      order(advertisements[:created_at].send(direction))
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_category_id, lambda { |category_ids|
    where(category_id: [*category_ids])
  }

  delegate :ad_title, to: :advertisement, prefix: true

  def self.options_for_sorted_by
    [
      [I18n.t('filter.new_first'), 'created_at_desc'],
      [I18n.t('filter.old_first'), 'created_at_asc']
    ]
  end
end

app/controllers/advertisements_controller.rb
# frozen_string_literal: true

class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: %i[show edit update destroy]
  before_action :set_categories

  load_and_authorize_resource

  before_action :authenticate_user!, except: %i[index show]

  def index
    (@filterrific = initialize_filterrific(
      Advertisement.where(state: :published), params[:filterrific],
      select_options: {
        sorted_by: Advertisement.options_for_sorted_by,
        with_category_id: Category.options_for_select
      }
    )) || return
    @advertisements = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  def new
    @advertisement = Advertisement.new
  end

  def edit; end

  def create
    @advertisement = current_user.advertisements.new(advertisement_params)

    if @advertisement.save
      redirect_to @advertisement, success: I18n.t('advertisement.create_action.success')
    else
      flash[:danger] = I18n.t('advertisement.create_action.danger')
      render 'new'
    end
  end

  def update
    if @advertisement.update(advertisement_params)
      redirect_to @advertisement, success: I18n.t('advertisement.edit.success')
    else
      flash[:danger] = I18n.t('advertisement.edit.danger')
      render 'edit'
    end
  end

  def destroy
    @advertisement.destroy

    redirect_to advertisements_path, success: I18n.t('advertisement.destroy.success')
  end

  def user_advertisements
    @advertisements = @current_user.advertisements.order('updated_at DESC')
    @states = Advertisement.state_machine.states.map &:value
  end

  def opened_advertisements
    @advertisements = Advertisement.where(state: 'opened')
  end

  private

  def set_categories
    @categories = Category.all
  end

  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:ad_title, :ad_text, :category_id, :state_event, pictures: [])
  end
end

app/helpers/advertisements_helper.rb
# frozen_string_literal: true

module AdvertisementsHelper
end

app/views/advertisements/_advertisements.html.slim
- @advertisements.each do |advertisement|
  article.advertisement
    - if advertisement.pictures.any?
      = image_tag advertisement.pictures.first.url, class: 'ads-picture col-12 col-md-3'
    - else
      = image_tag "/missing-image.png", class: 'ads-picture col-12 col-md-3'
    .ads-body.col-12.col-md-9
      section.advertisement-head
        h2
          = link_to advertisement.ad_title, advertisement_path(advertisement)
        small
          time
            = advertisement.created_at.to_date.strftime("%d %B, %Y")
      section.advertisement-summary
        p
          = advertisement.ad_text

app/views/advertisements/_form.html.slim
= simple_form_for @advertisement, html: { multipart: true } do |f|
  = f.input :ad_title
  = f.input :ad_text, hint: "", hint_html: { id: "ads_text_length" }, input_html: { id: 'ads_text', onkeyup: 'advertisement_text_length()' }
  = f.input :category_id, collection: Category.order(:name), :include_blank => t('simple_form.placeholders.category.select')
  .field
    .image-sortable
      - @advertisement.pictures.each do |picture|
        .image
          = hidden_field :advertisement, :pictures, multiple: true, value:  picture.cache_name || picture.identifier
          = image_tag picture.url(:thumb)
          button.remove-image.btn.btn-outline-danger[type="button"]
            = t('common.delete')
      .image
        = f.file_field :pictures, multiple: true
    button.add-image.btn.btn-primary[type="button"]
      =t('simple_form.more_images')
  = f.button :submit, class: 'btn btn-primary'
  = link_to t('common.back'), :back, class: 'btn btn-outline-secondary'

app/views/advertisements/_list.html.slim
= will_paginate @advertisements, renderer: 'BootstrapPaginationHelper::LinkRenderer'
= render 'advertisements'
= will_paginate @advertisements, renderer: 'BootstrapPaginationHelper::LinkRenderer'

app/views/advertisements/_state_ads.slim
- @advertisements.where(state: state).each do |advertisement|
  article.advertisement
    - if advertisement.pictures.any?
      = image_tag advertisement.pictures.first.url(:thumb), class: 'ads-picture col-12 col-md-3'
    - else
      = image_tag "/missing-image.png", class: 'ads-picture col-12 col-md-3'
    .ads-body.col-12.col-md-9
      section.advertisement-head
        h2
          = link_to advertisement.ad_title, advertisement_path(advertisement)
        small
          time
            = advertisement.created_at.to_date.strftime("%d %B, %Y")
      section.advertisement-summary
        = advertisement.ad_text

app/views/advertisements/edit.html.slim
h1
  = t('advertisements.edit.title')
= render 'form'

app/views/advertisements/index.html.slim
- breadcrumb :advertisements, @advertisement
h1
  = t('advertisement.index.title')
- if user_signed_in? && current_user.has_role?(:user)
  = link_to t('advertisement.create'), new_advertisement_path, class: "btn btn-primary"
.card.card-body.bg-light
  - puts @filterrific.inspect
  = form_for_filterrific @filterrific do |f|
    .row
      .col-md-6
        .form-group
          label.font-weight-bold
            = t('advertisement.type')
          = f.select :with_category_id, @filterrific.select_options[:with_category_id], {:include_blank => t('advertisement.select_type')} , :class => 'form-control'
      .col-md-6
        .form-group
          label.font-weight-bold
            = t('advertisement.sorting')
          = f.select :sorted_by, @filterrific.select_options[:sorted_by], {}, :class => 'form-control'
    .filter-navigation
      .col-md-10
        = page_entries_info @advertisements, :model => 'advertisement', :class => 'align-middle'
      .col-md-2
        = link_to t('filter.reset'), reset_filterrific_url, :class => 'btn btn-secondary'
#results
  = render :partial => 'advertisements/list'

app/views/advertisements/index.js.erb
<% js = escape_javascript(
  render( :partial => 'advertisements/list' )
) %>
$("#results").html("<%= js %>");

app/views/advertisements/new.html.slim
h1
  = I18n.t('advertisement.new.title')
= render 'form'

app/views/advertisements/opened_advertisements.html.slim
h1
  = t('navigation.new_advertisements')
= render 'advertisements'

app/views/advertisements/show.html.slim
- breadcrumb @advertisement
article.advertisement-card
  section.advertisement-head
    h1
      = @advertisement.ad_title
    small
      time
        = @advertisement.created_at.to_date.strftime("%d %B, %Y ")
      span
        | [
        = t("attributes.advertisement.states.#{@advertisement.state}")
        | ]
  section.advertisement-body
    - if @advertisement.pictures.any?
      - @advertisement.pictures.each do |picture|
        = image_tag picture.url, class: 'ads-picture'
    - else
      = image_tag "/missing-image.png", class: 'ads-picture'
    p
      = @advertisement.ad_text
  section.advertisement-author
    p
      = t('advertisement.author')
      = link_to @advertisement.user.username, @advertisement.user
  section.ads-btn
    - if user_signed_in?
      - if @advertisement.can_be_drafted?(current_user)
        = link_to t('advertisement.events.change'), [@advertisement, advertisement: {state_event: :change}], method: :patch, class: 'btn btn-primary'
      - if @advertisement.can_be_started?(current_user)
        = link_to t('advertisement.events.start'), [@advertisement, advertisement: {state_event: :start}], method: :patch, class: 'btn btn-primary'
      - if @advertisement.can_be_approved_or_rejected?(current_user)
        = link_to t('advertisement.events.approve'), [@advertisement, advertisement: {state_event: :approve}], method: :patch, class: 'btn btn-success'
        = link_to t('advertisement.events.reject'), [@advertisement, advertisement: {state_event: :reject}], method: :patch, class: 'btn btn-danger'
      - if @advertisement.can_be_edited?(current_user)
        = link_to t('common.edit'), edit_advertisement_path, class: "btn btn-warning"
      - if @advertisement.can_be_deleted?(current_user)
        = link_to t('common.delete'), advertisement_path,
                             method: :delete,
                             class: 'btn btn-outline-danger',
                             data: { confirm: 'Вы уверены?' }

app/views/advertisements/user_advertisements.html.slim
h1
  = t('advertisement.my')
ul#myTab.nav.nav-tabs[role="tablist"]
  - @states.each do |state|
    li.nav-item
      a [
        class = (state == @states.first ? 'nav-link active' : 'nav-link')
        id = "#{state} tab"
        data-toggle='tab'
        href = "##{state}"
        role = "tab"
        aria-controls = state
        aria-selected = (state == @states.first && "true")
      ] = t("attributes.advertisement.states.#{state}")
#myTabContent.tab-content
  - @states.each do |state|
    div [
    class = (state == @states.first ? "tab-pane fade active show" : "tab-pane fade")
    id = state
    role = "tabpanel"
    aria-labelledby = "state-tab"
    ]
      - if @advertisements.where(state: state).any?
        = render partial: 'state_ads', :locals => { :state => state }
      - else
        p
          = t('advertisement.missing', state: t("attributes.advertisement.states.#{state}"))