config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, path_prefix: 'my'
    resources :users

    get 'welcome/index'
    root 'welcome#index'

    get '/search' => 'search#search', as: :search

    resources :advertisements
    resources :categories

    get '/my_advertisements' => 'advertisements#user_advertisements', :as => :custom_user_advertisements
    get '/opened_advertisements' => 'advertisements#opened_advertisements', :as => :opened_advertisements
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end
end

app/views/layouts/_navbar.html.slim
.container
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    a.navbar-brand[href="/"]
      | ADS PROJECT
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to t('models.advertisements'), advertisements_path, class: 'nav-link'
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
            = t('models.categories')
          .dropdown-menu[aria-labelledby="navbarDropdown"]
            - @categories.each do |category|
              = link_to t("attributes.category.id.#{category.id}"), category_path(category), class: 'nav-link'
        - if user_signed_in? && current_user.has_role?(:admin)
          li.nav-item
            = link_to t('models.users'), users_path, class: "nav-link"
          li.nav-item
            = link_to t('models.categories'), categories_path, class: "nav-link"
          li.nav-item
            = link_to t('navigation.new_advertisements'), opened_advertisements_path, class: "nav-link"
        li.nav-item
          = link_to t('search'), search_path, class: "nav-link"
      ul.navbar-nav.float-right
        - if user_signed_in?
          li.nav-item.dropdown
            a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
              = current_user.email
            .dropdown-menu[aria-labelledby="navbarDropdown"]
              - if current_user.has_role?(:user)
                = link_to t('navigation.my_advertisements'), custom_user_advertisements_path, class: "dropdown-item"
              = link_to t('devise.links.edit_profile'), edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to t('devise.links.sign_out'), destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          li.nav-item
            = link_to t('devise.links.sign_in'), new_user_session_path, class: "nav-link"
          li.nav-item
            = link_to t('devise.links.sign_up'), new_user_registration_path, class: "nav-link"
        li class = (I18n.locale == :ru ? "nav-item active" : "nav-item")
          = link_to "RU", { locale: :ru }, class: "nav-link"
        li class = (I18n.locale == :en ? "nav-item active" : "nav-item")
          = link_to "EN", { locale: :en }, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Ads
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    .container.main
      .row
        .col-md-12
          - flash.each do |name, message|
            div [
              class = "alert #{bootstrap_class_for(name)}"
              ]
              button.close[data-dismiss="alert"]
                | ×
              = message
    .container.main
      = raw breadcrumbs style: :bootstrap, separator: "&nbsp;&rsaquo;&nbsp;"
      = yield